version: '3'
services:
  shadowsocks:
    image: hopher/shadowsocks-libev:latest
    container_name: my_shadowsocks
    ports:
    
      - "8388:8388/udp"
    build:
      context: .
    environment:
      - METHOD=rc4 # 加密方法
      - PASSWORD=170826  # 密码
    restart: always