version: '3'
services:
  shadowsocks:
    image: hopher/shadowsocks-libev:latest
    container_name: chat
    ports:
    
      - "80:80/tcp"
      - "80:80/udp"
    build:
      context: .
    environment:
     - PORT=80 
      - METHOD=rc4 # 加密方法
      - PASSWORD=170826  # 密码
    restart: always